Cards from System Gateway spoiler season
NetrunnerDB/netrunner-cards-json pull request #561
Opened 2021-03-19 19:29 UTC by mxmxyz

Some new HB cards and some new Criminal cards, respectively from [here](https://kitchentablenetrunner.podbean.com/e/episode-22-getting-better-and-gateway-scoops/) and [here](https://www.youtube.com/watch?v=4YsBncJQvVQ).

First time contributing to the repo so tell me if I did something wrong.

2021-03-19 21:24 UTC, gereons commented
Thanks for your contribution! Please make sure to run the included `validate.py` script when submitting a PR, this check is currently failing and must be "green" (ie, report 0 formatting and validation errors) for us to accept the PR.

These are the errors currently reported:

```
Validation error in card: (pack code: 'sg' card code: '30040' title: 'Seamless Launch')
u'operation' is not one of [u'asset', u'upgrade']

Validation error in card: (pack code: 'sg' card code: '30041' title: 'Sprint')
u'operation' is not one of [u'asset', u'upgrade']
```

2021-03-19 21:31 UTC, gereons requested changes

2021-03-19 21:31 UTC, gereons commented on pack/sg.json
> +        "text": "+1[mu]\nWhenever you make a successful run, place 1[credit] on this hardware.\n[click]: Place 1[credit] on this hardware, then take all credits from it.\nLimit 1 console per player."
"console" should be in a \<strong> tag

2021-03-19 21:31 UTC, gereons commented on pack/sg.json
> +        "type_code": "operation",
This can't be right

2021-03-19 21:31 UTC, gereons commented on pack/sg.json
> +        "type_code": "operation",
This can't be right

2021-03-20 01:36 UTC, plural commented
hey there!  Thanks for the patch!

We (NISEI web dev team) are actually going to publish everything that was spoiled during community week on Sunday.  We'll wrap things up on the 28th with the final cards. Keep an eye on the repo past this month though, and reach out if you see any other patches you wanna contribute.

2021-03-20 09:20 UTC, mxmxyz commented
I will, thank you for your work ^^

2021-03-22 08:47 UTC, gereons commented
Closing this in favor of #562

2021-03-22 08:47 UTC, closed without merging