Update the card text for Card Text Updates 1.2
NetrunnerDB/netrunner-cards-json pull request #600
Opened 2021-11-23 04:10 UTC by plural

https://nisei.net/blog/card-text-updates-1-2/

2021-11-23 07:47 UTC, gereons requested changes

2021-11-23 07:47 UTC, gereons commented on pack/cac.json
> +        "text": "You have +1 allotted [click} on your turn.\nWhen this asset is trashed from anywhere while being accessed, add it to the Runner's score area as an agenda worth 2 agenda points.",
`[click}` seems wrong

2021-11-23 07:47 UTC, gereons commented on pack/df.json
> +        "stripped_text": "When your discard phase ends, if you installed this resource this turn, draw 4 cards. interrupt -> The first time each turn you would draw any number of cards, increase the
`Interrupt` should remain capitalized, IMHO

2021-11-26 19:04 UTC, plural commented
thanks!

2021-11-26 20:43 UTC, gereons approved these changes

2021-11-26 23:20 UTC, merged