Add faction colors for mini-factions.
NetrunnerDB/netrunner-cards-json pull request #671
Opened 2022-06-21 00:06 UTC by plural

Address #547 in this repo, at least.  NRDB ... doesn't appear to use these colors, but i know the discord bot does and we may use them in other places.

2022-06-21 07:35 UTC, distributive requested changes
They do actually appear on the site as profile colors:
![image](https://user-images.githubusercontent.com/26557961/174742139-6f5ac221-12cb-4023-998e-cb6ff82382e9.png)

Looking at this I think Sunny might be too close to the neutral color. I took a leaf from GLC's book and used the purple tone from her background:
![image](https://user-images.githubusercontent.com/26557961/174742122-06ed7486-0d4d-4e0c-bc33-e3442b1b93d4.png)

2022-06-21 07:35 UTC, distributive commented on v2/factions.json
> +    "color": "6E6E6E",
```suggestion
    "color": "786196",
```

2022-06-23 04:35 UTC, plural commented
my local instance is not showing anything different here.  :/

Additionally, the css has its own, literal, copy of the colors.  :/

2022-06-23 22:56 UTC, distributive commented
Classic NetrunnerDB

2022-06-23 22:57 UTC, distributive approved these changes

2022-06-25 03:27 UTC, merged